#!/bin/bash
#
# Apache2 Access Log by IP
#   Displays the IP addresses that have connected to the webserver
#
echo "The following IP Addresses have connected to the webserver:"
awk '{ print $1 } ' /var/log/apache2/access.log | sort -nr | uniq -c
